// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4l47GEG9IyHI_N5kx4ZwGpvGJ6uAc3uk',
    appId: '1:674233901372:android:2a2273cab675cf55e13e39',
    messagingSenderId: '674233901372',
    projectId: 'cryptotradex-de989',
    storageBucket: 'cryptotradex-de989.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwxOI_a0RX93nm8OKPRO9rTYqEu_fZALM',
    appId: '1:674233901372:ios:a3cafd704048c800e13e39',
    messagingSenderId: '674233901372',
    projectId: 'cryptotradex-de989',
    storageBucket: 'cryptotradex-de989.appspot.com',
    iosBundleId: 'com.example.cryptotradex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwxOI_a0RX93nm8OKPRO9rTYqEu_fZALM',
    appId: '1:674233901372:ios:d6fe419d7c9d9c4de13e39',
    messagingSenderId: '674233901372',
    projectId: 'cryptotradex-de989',
    storageBucket: 'cryptotradex-de989.appspot.com',
    iosBundleId: 'com.example.cryptotradex.RunnerTests',
  );
}
